#!/bin/sh

. /etc/rc.subr

name="mmsite"
workers="10"
path="/usr/home/http/Mmsite/"
sockfile="${path}/tmp/sock.sock"
pidfile="${path}/tmp/${name}.pid"
appfile="${path}/bin/app.psgi"
plackupfile="/usr/local/bin/plackup"
logfile="${path}/logs/server.log"
user="http"

rcvar=`set_rcvar`

start_cmd="${name}_start"
stop_cmd="${name}_stop"

mmsite_start()
{
    echo "starting..."
    su ${user} -c "cd ${path}; ${plackupfile} -E production -s Starman -workers=${workers} -S ${sockfile} -a ${appfile} --pid ${pidfile} >> ${logfile} 2>&1 &"
}

mmsite_stop()
{
    echo "stoping..."
    cat ${pidfile} | xargs kill
}


load_rc_config $name
run_rc_command "$1"
